{% set name = "kim-property" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45b9265cd3d1b66f5dba230ae7e2862bd0ba379e34aee51b4780a00ff5d897b9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - versioneer >=0.29
    - kim-edn >=1.4.1
  run:
    - python >=3.8
    - kim-edn >=1.4.1

test:
  imports:
    - kim_property

about:
  home: https://github.com/openkim/kim-property
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: KIM-PROPERTY utility module
  description: |
    KIM-PROPERTY utility module.
    The objective is to make it as easy as possible to convert a script (for
    example a [LAMMPS](https://lammps.sandia.gov/) script) that computes a
    property to a KIM Test.

extra:
  recipe-maintainers:
    - yafshar
