{% set name = "kim-property" %}
{% set version = "2.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e7616beca3355a57e11dde8c0cb1ee537c6cf80182fd7277a8462d6f721fa0b4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer >=0.29
    - kim-edn >=1.4.1
  run:
    - python >={{ python_min }}
    - kim-edn >=1.4.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - kim_property

about:
  home: https://github.com/openkim/kim-property
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: KIM-PROPERTY utility module
  description: |
    KIM-PROPERTY utility module.
    The objective is to make it as easy as possible to convert a script (for
    example a [LAMMPS](https://lammps.sandia.gov/) script) that computes a
    property to a KIM Test.

extra:
  recipe-maintainers:
    - yafshar
