{% set name = "kim-property" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4dec677ee50815d9c34dab4fba97c7cb67f9d7b47c46cfecb8d9a01fe785648a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=80
    - setuptools-scm >=9.2
  run:
    - python >={{ python_min }}
    - kim-edn >=1.4.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - kim_property
  commands:
    - pip check

about:
  home: https://github.com/openkim/kim-property
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Create, modify, validate, and serialize OpenKIM Property Instances
  description: |
    kim-property provides utilities to create, destroy, modify, remove fields
    from, validate, and serialize OpenKIM Property Instances. It is intended
    to simplify converting scripts that compute material properties into KIM
    Tests. kim-property supports Python 3.10 and later.
  doc_url: https://github.com/openkim/kim-property#readme
  dev_url: https://github.com/openkim/kim-property

extra:
  recipe-maintainers:
    - yafshar
