{% set name = "kim-property" %}
{% set version = "2.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2605ef013771db0b2fc43584f5db61f2e5a6670831fe686e241c6d0653a802d9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - kim-edn

test:
  imports:
    - kim_property

about:
  home: https://github.com/openkim/kim-property
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: KIM-PROPERTY utility module
  description: |
    KIM-PROPERTY utility module.
    The objective is to make it as easy as possible to convert a script (for
    example a [LAMMPS](https://lammps.sandia.gov/) script) that computes a
    property to a KIM Test.

extra:
  recipe-maintainers:
    - yafshar
