{% set name = "kim-property" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86b3bf80b96d63c0e3d56c0dca40555c1ac67429086164bd5dcb1e920a9e5aba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - kim_edn

test:
  imports:
    - kim_edn
    - kim_property

about:
  home: https://github.com/openkim/kim-property
  license: CDDL-1.0
  license_family: OTHER
  license_file: LICENSE.CDDL
  summary: KIM-PROPERTY utility module
  description: |
    KIM-PROPERTY utility module.
    The objective is to make it as easy as possible to convert a script (for
    example a [LAMMPS](https://lammps.sandia.gov/) script) that computes a
    property to a KIM Test.

extra:
  recipe-maintainers:
    - yafshar
